### ISSUE TITLE
Can "engines.node" removed from package.json?

### ISSUE THREAD

**Issue by dan-dr** [kennethormandy/react-fittext#1]
yarn is panicking with `error @kennethormandy/react-fittext@0.3.0: The engine "node" is incompatible with this module. Expected version "^8.x".` when my node version is 9.8.0

Really annoying to add a --ignore-engines every time :)

Maybe `"node": ">= 8.x"` will work as well

**Comment by kennethormandy** [comment]
I can see how that would be annoying! If you don’t mind opening a Pull Request for the second solution, I’d be happy to merge it.

Thanks for opening an issue.
